require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ChallengesController do

  def mock_challenge(stubs={})
    @mock_challenge ||= mock_model(Challenge, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all challenges as @challenges" do
      Challenge.stub(:all) { [mock_challenge] }
      get :index
      assigns(:challenges).should eq([mock_challenge])
    end
  end

  describe "GET show" do
    it "assigns the requested challenge as @challenge" do
      Challenge.stub(:find).with("37") { mock_challenge }
      get :show, :id => "37"
      assigns(:challenge).should be(mock_challenge)
    end
  end

  describe "GET new" do
    it "assigns a new challenge as @challenge" do
      Challenge.stub(:new) { mock_challenge }
      get :new
      assigns(:challenge).should be(mock_challenge)
    end
  end

  describe "GET edit" do
    it "assigns the requested challenge as @challenge" do
      Challenge.stub(:find).with("37") { mock_challenge }
      get :edit, :id => "37"
      assigns(:challenge).should be(mock_challenge)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created challenge as @challenge" do
        Challenge.stub(:new).with({'these' => 'params'}) { mock_challenge(:save => true) }
        post :create, :challenge => {'these' => 'params'}
        assigns(:challenge).should be(mock_challenge)
      end

      it "redirects to the created challenge" do
        Challenge.stub(:new) { mock_challenge(:save => true) }
        post :create, :challenge => {}
        response.should redirect_to(challenge_url(mock_challenge))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved challenge as @challenge" do
        Challenge.stub(:new).with({'these' => 'params'}) { mock_challenge(:save => false) }
        post :create, :challenge => {'these' => 'params'}
        assigns(:challenge).should be(mock_challenge)
      end

      it "re-renders the 'new' template" do
        Challenge.stub(:new) { mock_challenge(:save => false) }
        post :create, :challenge => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested challenge" do
        Challenge.stub(:find).with("37") { mock_challenge }
        mock_challenge.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :challenge => {'these' => 'params'}
      end

      it "assigns the requested challenge as @challenge" do
        Challenge.stub(:find) { mock_challenge(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:challenge).should be(mock_challenge)
      end

      it "redirects to the challenge" do
        Challenge.stub(:find) { mock_challenge(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(challenge_url(mock_challenge))
      end
    end

    describe "with invalid params" do
      it "assigns the challenge as @challenge" do
        Challenge.stub(:find) { mock_challenge(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:challenge).should be(mock_challenge)
      end

      it "re-renders the 'edit' template" do
        Challenge.stub(:find) { mock_challenge(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested challenge" do
      Challenge.stub(:find).with("37") { mock_challenge }
      mock_challenge.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the challenges list" do
      Challenge.stub(:find) { mock_challenge }
      delete :destroy, :id => "1"
      response.should redirect_to(challenges_url)
    end
  end

end
